CREATE TABLE [orders] (
  [id] TEXT,
  [clientOrderId] TEXT,
  [datetime] TEXT,
  [timestamp] INTEGER,
  [lastTradeTimestamp] INTEGER,
  [lastUpdateTimestamp] INTEGER,
  [status] TEXT,
  [symbol] TEXT,
  [type] TEXT,
  [timeInForce] TEXT,
  [side] TEXT,
  [price] REAL,
  [average] REAL,
  [amount] REAL,
  [filled] REAL,
  [remaining] REAL,
  [stopPrice] REAL,
  [takeProfitPrice] REAL,
  [stopLossPrice] REAL,
  [cost] REAL,
  [TUSD_to_EURO] REAL,
  [trades] TEXT,
  [fee] TEXT
);